server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: info,health

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail.sender}
    password: ${gmail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true