server:
  port: ${env.PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: info,health

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${env.GMAIL_SENDER}
    password: ${env.GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true